### PR TITLE
[foxy] Generate Setuptools Dict Helper Method

### PR DESCRIPTION
**Pull request by DLu**
#126 cherry-picked into Foxy!

### CODE REVIEW

**Comment by DLu** [comment]
Okay, finally ready for review @audrow

**Review by audrow — APPROVED** [review]

**Comment by audrow** [comment]
Just in case, since there's no PR job for this repo:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13891/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8742/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11599/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13981/)

**Comment by audrow** [comment]
Thanks for the backport, @DLu!

**Comment by DLu** [comment]
Thanks for the merge! Could I get a new release as well?

**Comment by audrow** [comment]
Sure, I'll try to do it tomorrow.

**Comment by audrow** [comment]
Here's the release PR: https://github.com/ros/rosdistro/pull/28628

**Pull request merged**
