### PR TITLE
support more operators in conditions

### PR DESCRIPTION
**Pull request by dirk-thomas**
Implementing the change from ros-infrastructure/rep#146.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
> I'm assuming that the tests pass locally

:pray: :+1:

**Comment by dhood** [comment]
http://ci.ros2.org/job/ci_linux-aarch64/874/testReport/junit/ament_package.test/test_flake8/test_flake8/ :stuck_out_tongue:

**Comment by dirk-thomas** [comment]
Doh :disappointed: I just re-ran the tests locally again and they still passed.

After some digging it turns out that the new version of the flake8-import-order (0.16) seems to be more picky than the version I had locally (1.13). I committed the referenced fix to master.

Thanks for pointing it out.

**Comment by dhood** [comment]
it's happened to all of us I think (well, myself at least)!

**Comment by dirk-thomas** [comment]
I guess that is why we don't recommend users to install stuff via pip - since it doesn't get updated regularly like apt...

**Pull request merged**
