### PR TITLE
Always consider .dsv files, even when no shell specific script exists

### LINKED ISSUE #145: `.dsv` files are not processed unless there is `.sh` file with the same base name
When using `ament_environment_hooks`, `.dsv` files not processed properly unless there is a `.sh` file with the same name registered with `ament_environment_hooks`. This `.sh` file can be an empty file.

The issue appears to be with `ament_package` since building this package with `colcon` doesn't exhibit the same problem.

MWE: https://github.com/azeey/sandbox/tree/master/test_ament_pkg

It seems like https://github.com/ament/ament_package/blob/35b15ae4d8c5e1dbb6ab622ff95d046aa3ca1b28/ament_package/template/prefix_level/_local_setup_util.py#L257 only processes files with `primary_extension` or `additional_extension`, which in my system were `.sh` and `.zsh`, so `.dsv` files seem to be ignored.

Potential fix (works for me locally):

```diff
diff --git a/ament_package/template/prefix_level/_local_setup_util.py b/ament_package/template/prefix_level/_local_setup_util.py
index fe2afda..29849f3 100644
--- a/ament_package/template/prefix_level/_local_setup_util.py
+++ b/ament_package/template/prefix_level/_local_setup_util.py
@@ -254,7 +254,7 @@ def process_dsv_file(
             path_without_ext, ext = os.path.splitext(remainder)
             assert ext.startswith('.')
             ext = ext[1:]
-            if ext in (primary_extension, additional_extension):
+            if ext in (primary_extension, additional_extension, 'dsv'):
                 if path_without_ext not in basenames:
                     basenames[path_without_ext] = set()
                 basenames[path_without_ext].add(ext)
```

### PR DESCRIPTION
**Pull request by azeey**
Fix #145 

Copy of https://github.com/colcon/colcon-core/pull/244/commits/3697164b248d578ec15e9f0d369d005cf1d9894a

### CODE REVIEW

**Review by sloretz — APPROVED** [review]
LGTM with green CI once [the freeze is finished](https://discourse.ros.org/t/freeze-of-ros-2-base-packages-upcoming-branch-and-tutorial-party-for-jazzy-jalisco/37191)

**Comment by MichaelOrlov** [comment]
@sloretz  Friendly ping to follow up on this PR since Rolling freeze has already been lifted.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20950/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15242/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21624/)

**Comment by azeey** [comment]
@Mergifyio backport jazzy

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
