### PR TITLE
add warning/fallback for AMENT_CURRENT_PREFIX if relocated

### PR DESCRIPTION
**Pull request by dirk-thomas**
Resolves colcon/colcon-ros#67.

### CODE REVIEW

**Comment by murphm8** [comment]
I have confirmed this fixes colcon/colcon-ros#67

**Comment by murphm8** [comment]
Will this be able to make it into the 27th Dashing patch release?

**Comment by nuclearsandwich** [comment]
> Will this be able to make it into the Aug 27th Dashing patch release?

No. The Dashing sync planned for that date does not include a patch release for ROS 2 core packages.

**Comment by dirk-thomas** [comment]
> Will this be able to make it into the Aug 27th Dashing patch release?

Yes, I will backport the patch and do a bloom release of this package to be part of the sync.

**Comment by dirk-thomas** [comment]
Since this commit is the only change compared to the `dashing` branch I fast-forward merged the change to the `dashing` branch.

I tagged a new version 0.7.1 and also fast-forwarded it to keep `dashing` and `master` in sync.

**Comment by dirk-thomas** [comment]
ros/rosdistro#22070.

**Comment by murphm8** [comment]
Thanks for this solution!

**Pull request merged**
