### PR TITLE
add quotes around ament_python_executable variable in local_setup.bat

### LINKED ISSUE #84: local_setup.bat fails if PYTHON_EXECUTABLE contains parentheses
Evidently parentheses need to be escaped with `^` when used in a `for /f`, even if double-quoted. Without this fix, I get messages like:
```
/Microsoft was unexpected at this time.
```

Workaround is to modify the generated `local_setup.bat` and escape the parentheses with carats like this:
```
...
  set "ament_python_executable=C:/Program Files ^(x86^)/Microsoft Visual Studio/Shared/Python37_64/python.exe"
...
```

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes (update: no it doesn't) #84.

### CODE REVIEW

**Comment by cottsay** [comment]
This does not fix #84, but might still be goodness.

**Comment by cottsay** [comment]
When does the `isolated_prefix_level` version of `local_setup.bat` get used? Or rather, how can I test this change?

**Comment by dirk-thomas** [comment]
Actually I don't think the `isolated_prefix_level` files are used anymore. `ament_tools` used them but `colcon` has its own. So this change is probably not necessary.

Even if we remove those file in the future I think fixing the bat code would still be good in case we look back...

**Comment by dirk-thomas** [comment]
The second commit adds the same fix as in #91.

**Pull request merged**
