### PR TITLE
Add support for comment lines in dsv files

### PR DESCRIPTION
**Pull request by cottsay**
Paris with colcon/colcon-core#550

This is a pretty containable change, and should be considered for backport to supported distros.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I somehow completely overlooked the reference to this PR in https://github.com/colcon/colcon-core/pull/550 luckily this was the next PR in my review queue.

**Review by nuclearsandwich — APPROVED** [review]
Repeating myself from the colcon review a little: I'm a bit shy about adding comments to the format without knowing how many parsers are out there, but I have no strong objection.

Parsing commented dsv files is not a "breaking" change but adding comments to a previously uncommented dsv would be in my opinion. So we should watch out for that in core places where dsv files are used.

**Comment by cottsay** [comment]
> Parsing commented dsv files is not a "breaking" change but adding comments to a previously uncommented dsv would be in my opinion. So we should watch out for that in core places where dsv files are used.

I agree :100:. The goal here is to make comment parsing support widespread as soon as possible so that someday we can start using them, but definitely not soon.

**Comment by nuclearsandwich** [comment]
> I agree 100. The goal here is to make comment parsing support widespread as soon as possible so that someday we can start using them, but definitely not soon.

Are there any tests on the dsv parser? Introducing a unit tests that tackles comments would be a good signal to any alternative implementations but if there's no tests for it at all then that's a good first-time-contributor bug to file.

**Comment by cottsay** [comment]
> Are there any tests on the dsv parser? Introducing a unit tests that tackles comments would be a good signal to any alternative implementations but if there's no tests for it at all then that's a good first-time-contributor bug to file.

None that I'm aware of, even on colcon :(

**Pull request merged**
