### PR TITLE
adding more quotes to work with paths including whitespaces

### PR DESCRIPTION
**Pull request by tfoote**
Connects to ros2/ros2#20

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by dirk-thomas** [comment]
Did you quote all variables. For some of them it does not seem to make sense, e.g. `*_IFS`. I think we should only quote the ones necessary.

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
The IFS ones were not required. Removed.

**Comment by dirk-thomas** [comment]
Before merging this (and the related PRs) I would like to see a workspace with whitespaces building successfully. Currently that seems to be not yet the case - at least for me - see https://github.com/ament/ament_tools/pull/28#issuecomment-88745262.

**Comment by tfoote** [comment]
I removed a few too many quotes in the comment cleanup. Added back in 216bb36

I can build with this and ament/ament_tools#28  it builds until idlpp hangs building the opensplice messages. and the following args  `--build-space "build space" --install-space "install space"`

**Comment by dirk-thomas** [comment]
I was able to build the full workspace (with OpenSplice being ignored for now).

**Pull request merged**
