### PR TITLE
Revert "Generate Setuptools Dict Helper Method (#126) (#128)"

### PR DESCRIPTION
**Pull request by audrow**
This reverts commit 4e69bf16021eff87cc2e30c8ff77c0a987bb3112.

I didn't find any other ROS2 packages in the [foxy repos file](https://github.com/ros2/ros2/blob/foxy/ros2.repos) that used the reverted feature.

### CODE REVIEW

**Comment by audrow** [comment]
Here is CI. I'm building all packages that use `ament_package` and testing only `ament_package`.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14407/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9180/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12081/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14505/)

**Comment by jacobperron** [comment]
Technically, since the change has been released, there could be users of the helper out in the wild. Removing it would break them, so I'm hesitant to remove it.

IIUC, as-is the helper won't work for people trying to release their packages on the buildfarm, though it might work in other contexts. Is that right? @nuclearsandwich @clalancette

**Comment by clalancette** [comment]
> Technically, since the change has been released, there could be users of the helper out in the wild. Removing it would break them, so I'm hesitant to remove it.

Yep, you are absolutely correct.  I didn't realize that this had been released and synced into a Foxy release.

In that case, I'm fine with just leaving it in.  In that case, I think we should *also* leave it in in Rolling/Galactic.  It isn't ideal, but it seems weird to have it in Foxy but not in Galactic.  @nuclearsandwich what do you think?

**Comment by nuclearsandwich** [comment]
> Technically, since the change has been released, there could be users of the helper out in the wild. Removing it would break them, so I'm hesitant to remove it.

There are no users of the helper on the build farm due since we'd have already seen the breakage.

> I think we should _also_ leave it in in Rolling/Galactic. It isn't ideal, but it seems weird to have it in Foxy but not in Galactic.

The feature is broken for its primary use case. I don't have any hesitation removing broken features. Leaving it in to me just seems like leaving a rake for people to step on.

There are packages that will never see the buildfarm which could use this feature as-is but I don't think that leaving it in is worth the confusion it will cause by breaking as soon as a package makes that transition.

I'm strongly against leaving it in Rolling and having it in Galactic because it puts unnecessary weight on making it work unmodified on the buildfarm in the future when I think that a more correct solution is potentially in reach down the line but would be a breaking change from how it is used here. Taking it out would give us more time to find an appropriate approach.

**Review by jacobperron — APPROVED** [review]
Considering that the feature has only been released into Foxy for a few days, I think it's better to remove it.

**Comment by audrow** [comment]
The warning in Window's CI is unrelated and should be fixed by https://github.com/ros2/rviz/pull/673.

**Pull request merged**
